djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
]

djangonautic/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'


urlpatterns = [
    path('', views.article_list, name='list'),
    path('<slug:slug>/', views.article_detail, name='detail')
]

djangonautic/djangonautic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', views.homepage),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns() # for static files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # for media files

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

    @classmethod
    def get_all(cls):
        return cls.objects.all()

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})

djangonautic/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse


# Create your views here.
def article_list(request):
    articles = Article.get_all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Sign up</h1>

<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        
        <h2>{{ article.title }}</h2>
        <p>{{ article.date }}</p>
        <p>{{ article.body }}</p>
    </div>
</div>

{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>

    <br>

    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>This is the About page</h1>
        <p>About</p>
    </body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}" >
    </head>
    <body>
        <div class="wrapper">
            <h2>
                <a href="{% url 'articles:list' %}" >
                    <img src="{% static 'logo.png' %}">
                </a>
            </h2>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangonautic/templates/homepage.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Djangonautic</p>
    </body>
</html>